name: Plugin Directory Updater
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [push]
  # schedule:
  #   - cron: '5 * * * *'

jobs:
  update-plugins:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run script to update plugins
      run: node .github/scripts/check-plugins.js
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Stage changes
      run: git add .
      continue-on-error: true

    - name: Show diff
      run: git diff --cached
